config/routes.rb
Rails.application.routes.draw do

  root 'films#index'

  resources :films do
    resources :opinions
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
  validates :premiere, presence: true, length: { minimum: 5 }
  validates :length, presence: true, length: { minimum: 2 }
  validates :country, presence: true, length: { minimum: 2 }
  validates :director, presence: true, length: { minimum: 5 }
  validates :screen_writer, presence: true, length: { minimum: 5 }
  validates :description, presence: true, length: { minimum: 5 }
  validates :category, presence: true, length: { minimum: 5 }

  has_many :opinions, dependent: :destroy

  def next_film
    Film.where("title > ?", title).order(:title).first
  end

  def previous_film
    Film.where("title < ?", title).order(:title).last
  end
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  validates :name, presence: true, length: { minimum: 5 }
  validates :surname, presence: true, length: { minimum: 5 }
  validates :text, presence: true, length: { minimum: 5 }
  validates :rate, presence: true, length: { minimum: 1 }

  belongs_to :film
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]

  def index
    @films = Film.all.order(:title)
  end

  def new
    @film = Film.new
  end

  def create
    @film = Film.create(film_params)

    if @film.new_record?
      render "new"
    else
      redirect_to film_path(@film)
    end
  end

  def show
    @film = Film.find(params[:id])
    @opinion = Opinion.new(film_id: @film.id)
    @next_film = @film.next_film
    @previous_film = @film.previous_film

  end

  def edit
    @film = Film.find(params[:id])
  end

  def update
    @film = Film.find(params[:id])

    if @film.update(film_params)
      redirect_to @film
    else
      render "edit"
    end
  end

  def destroy
    film = Film.find(params[:id])
    film.destroy


    redirect_to films_path
  end


  private

  def film_params
    params.require(:film).permit(:title, :premiere, :length, :description,
                                 :director, :country, :category,
                                 :screen_writer)
  end
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "admin", only: [:destroy]
 def create
   @film = Film.find(params[:film_id])
   @opinion = Opinion.new(film_id: @film.id)
   @opinion.attributes = opinion_params

   if @opinion.save
     redirect_to film_path(@film)
   else
     render "films/show"
   end
 end

 def destroy
   opinion = Opinion.find(params[:id])
   opinion.destroy

   redirect_to film_path(opinion.film)
 end

 private

 def opinion_params
    params.require(:opinion).permit(:name, :surname, :rate, :text)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/common/_errors.html.erb
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

<% if model.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(model.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>

    <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/films/_form.html.erb
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

<%= render "common/errors", model: @film %>
<%= form_for @film do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :premiere %><br>
    <%= f.text_field :premiere %>
  </p>

  <p>
    <%= f.label :length %><br>
    <%= f.text_field :length %>
  </p>

  <p>
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </p>

  <p>
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </p>

  <p>
    <%= f.label :screen_writer %><br>
    <%= f.text_field :screen_writer %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </p>


  <p>
    <%= f.submit%>
  </p>
<% end %>

app/views/films/edit.html.erb
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<h1 id = 'title'> Edit film </h1>

<%= render "form" %>

app/views/films/index.html.erb
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">

<h1 id='title'> All films! </h1>
<div id = 'films_list'>
  <% @films.each do |film| %>
    <p>
      <i class="material-icons md-light">movie</i>
      <%= link_to film.title, film_path(film), class: 'all_films' %>
    </p>
  <% end %>
</div>
<p> <%= link_to "Add film", new_film_path,  class: 'new_item' %> </p>

app/views/films/new.html.erb
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<h1 id='title'> Add new movie </h1>

<%= render "form" %>

<%= link_to "Back to all", films_path, class: 'new_item' %>

app/views/films/show.html.erb
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">

<h1 id = 'title'><%= @film.title %> </h1>

<div id = 'films_list'>
  <p> premiere :
  <span class = "inserts"><%= @film.premiere %> </span></p>

  <p> length :
  <span class = "inserts"><%= @film.length %> </span></p>

  <p> country :
  <span class = "inserts"><%= @film.country %> </span></p>

  <p> director :
  <span class = "inserts"><%= @film.director %> </span></p>

  <p> screenwriter :
  <span class = "inserts"><%= @film.screen_writer %> </span></p>

  <p> description :
  <span class = "inserts"><%= @film.description %> </span></p>

  <p> category :
  <span class = "inserts"><%= @film.category %> </span></p>
</div>

<i class="material-icons md-light">movie</i>

<% if @previous_film %>
  <i class="material-icons">keyboard_arrow_left</i>
  <%= link_to "Previous", film_path(@previous_film), class: 'new_item' %>
<% end %>

<%= link_to "Back to all", films_path, class: 'new_item' %>

<% if @next_film %>
  <%= link_to "Next", film_path(@next_film), class: 'new_item' %>
  <i class="material-icons">keyboard_arrow_right</i>
<% end %>

<h2 id = 'title2'> Add opinion </h2>

<%= render "opinions/form" %>

<h2 id = 'title2'> Oder opinions </h2>

<%= render @film.opinions%>





<%= link_to "Edit", edit_film_path(@film) %>
<%= link_to "Delete", film_path(@film),
                      method: :delete,
                      data: { confirm: "Why? tell me why?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KatalogFilmow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/opinions/_form.html.erb
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

<%= render "common/errors", model: @opinion %>

<div class = 'opinion_all'>
  <%= form_for [@film, @opinion] do |f| %>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :surname %>
      <%= f.text_field :surname %>
    </p>

    <p>
      <%= f.label "Your opinion" %>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.label "rate from 1 - 10, 10 means the best" %>
      <%= f.text_field :rate %>
    </p>

    <p>
      <%= f.submit %>
    </p>

  <% end %>
</div>

app/views/opinions/_opinion.html.erb
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

<div class = 'opinion_all'>
  <p> Person :
  <span><%= opinion.name %> <%= opinion.surname %> </span>

  <p> Opinion :
  <span><%= opinion.text %> </span>

  <p> Rating :
  <span><%= opinion.rate %> </span>

  <%= link_to "Delete opinion", film_opinion_path(@film, opinion),
                                method: :delete,
                                data: { confirm: "Don't you think about it?"}%>
</div>